spring.profiles.active=@spring.profiles.active@

server.port=8083

spring.application.name=paypal-provider-service

paypal.client.id=ARPevS9Y8_-qvuIRMkrnutgE0c4I4n9APy67mOqClpMYQeP5RJJMYQ2hsRXG1Q0JovdWn5vSZImP7MKC
paypal.outh.url=EDUkTKHM5B5ExZALMmD-P3boqYfuHHhxf_Hlh4PQRcJCaotJR18YgizZsDVKE01fN3tWcPgpxuLYuwcG
paypal.outhurl= https://api-m.sandbox.paypal.com/v1/oauth2/token
